import { SceneProps } from "@/types/project";

export const dummyScenes: SceneProps[] = [
  {
    id: "scene-1",
    intExt: "ext",
    location: "loc-1",
    time: "day",
    scriptDay: 1,
    sceneSource: "ai",
    synopsis:
      "Sam's drone catches something in the water she doesn't see yet — the audience is ahead of her. We're watching a creature circle beneath her feet while she's busy being delighted.",
    emotionalBeat:
      "The beat has to travel that full distance in under two minutes or the cliffhanger doesn't land. The delight phase needs to be genuine — we have to want what she wants before it's taken from her.",
    productionNotes: "",
    characters: [
      {
        id: "char-1",
        look: "Default look",
        wardrobe: ["wrd-4931", "wrd-4933"],
        props: ["prp-1"],
        tags: [],
      },
    ],
    props: [
      {
        id: "prp-4",
        name: "Sam's Paddleboard",
        look: "Default look",
        originCharacter: "char-1",
      },
    ],
    shots: [
      {
        id: "shot-1",
        label: "DRONE POV — OPENING",
        shotType: "wide",
        description:
          "Coming up from the water, reef below, Sam and board resolving into frame from above. Cinematic. This is the shot she's chasing. Hold on it. Let it be beautiful.",
      },
      {
        id: "shot-2",
        label: "SAM'S PHONE SCREEN - INSERT",
        shotType: "close",
        description:
          "The footage playing back in real time. Crisp. The reef edge. She watches it like she's watching herself win.",
      },
      {
        id: "shot-3",
        label: "WIDE — SAM ON BOARD",
        shotType: "wide",
        description:
          "Full figure, calm water, horizon behind her, drone visible above. Establishes scale and isolation in one frame. She is alone and the ocean is very large.",
      },
      {
        id: "shot-4",
        label: "SAM — MCU",
        shotType: "mid",
        description:
          'Her face when she says "Okay... okay. That is unreal." This is the peak of delight. Bank it. The audience needs to feel it so the turn hurts.',
      },
      {
        id: "shot-5",
        label: "DRONE POV — REFRAME DOWN",
        shotType: "wide",
        description:
          "The drone dips, lens pointing straight down. The reef below. Then at the edge of frame — the shadow. Moving. We see it before she does.",
      },
      {
        id: "shot-6",
        shotType: "close",
        label: "SAM'S PHONE SCREEN — INSERT",
        description: "The shadow on her screen. Her thumb hovers. Does she see it? Not yet.",
      },
      {
        id: "shot-7",
        label: "UNDERWATER — LOW ANGLE",
        shotType: "wide",
        description:
          "Optional but valuable if achievable: looking up at the underside of the board from below. The silhouette of Sam and the board on the surface. Something large moving into frame from the edge. Don't show it clearly. Show its scale.",
      },
      {
        id: "shot-8",
        label: "SAM — MCU",
        shotType: "mid",
        description:
          'The thump. Her body absorbs it. Her face goes from open to closed in a single frame. "Hey. Not funny." She thinks it\'s a person. She\'s wrong.',
      },
      {
        id: "shot-9",
        shotType: "wide",
        label: "WIDE — SAM SCANNING",
        description: "Searching for a boat, a person, a reasonable",
      }
    ]
  },
  {
    id: "scene-2",
    intExt: "ext",
    location: "loc-2",
    time: "night",
    scriptDay: 1,
    sceneSource: "ai",
    synopsis: "",
    emotionalBeat: "",
    productionNotes: "",
    characters: [],
    props: [],
  },
  {
    id: "scene-3",
    intExt: "int",
    location: "loc-3",
    time: "day",
    scriptDay: 1,
    sceneSource: "ai",
    synopsis: "",
    emotionalBeat: "",
    productionNotes: "",
    characters: [],
    props: [],
  },
  {
    id: "scene-4",
    intExt: "ext",
    location: "loc-4",
    time: "day",
    scriptDay: 1,
    sceneSource: "ai",
    synopsis: "",
    emotionalBeat: "",
    productionNotes: "",
    characters: [],
    props: [],
  },
  {
    id: "scene-5",
    intExt: "int",
    location: "loc-5",
    time: "day",
    scriptDay: 1,
    sceneSource: "ai",
    synopsis: "",
    emotionalBeat: "",
    productionNotes: "",
    characters: [],
    props: [],
  },
  {
    id: "scene-6",
    intExt: "ext",
    location: "loc-6",
    time: "Night",
    scriptDay: 2,
    sceneSource: "ai",
    synopsis: "",
    emotionalBeat: "",
    productionNotes: "",
    characters: [],
    props: [],
  },
  {
    id: "scene-7",
    intExt: "int",
    location: "loc-7",
    time: "day",
    scriptDay: 3,
    sceneSource: "ai",
    synopsis: "",
    emotionalBeat: "",
    productionNotes: "",
    characters: [],
    props: [],
  },
  {
    id: "scene-8",
    intExt: "ext",
    location: "loc-8",
    time: "Night",
    scriptDay: 3,
    sceneSource: "ai",
    synopsis: "",
    emotionalBeat: "",
    productionNotes: "",
    characters: [],
    props: [],
  },
  {
    id: "scene-9",
    intExt: "int",
    location: "loc-9",
    time: "day",
    scriptDay: 4,
    sceneSource: "ai",
    synopsis: "",
    emotionalBeat: "",
    productionNotes: "",
    characters: [],
    props: [],
  },
  {
    id: "scene-10",
    intExt: "ext",
    location: "loc-10",
    time: "Night",
    scriptDay: 4,
    sceneSource: "ai",
    synopsis: "",
    emotionalBeat: "",
    productionNotes: "",
    characters: [],
    props: [],
  },
];